# Generated by Django 2.2.2 on 2019-10-16 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockdata',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='gross_value',
            field=models.DecimalField(decimal_places=6, max_digits=20, verbose_name='Gross Value'),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='high',
            field=models.DecimalField(decimal_places=6, max_digits=20, verbose_name="Day's high"),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='low',
            field=models.DecimalField(decimal_places=6, max_digits=20, verbose_name="Day's low"),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='quarter',
            field=models.DecimalField(decimal_places=6, max_digits=20, verbose_name="Day's quarter"),
        ),
        migrations.AlterField(
            model_name='user',
            name='firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='main.Firm', verbose_name='Company'),
        ),
    ]
